### ISSUE TITLE
Organize own courses by year

### ISSUE THREAD

**Issue by Mixone-FinallyHere** [DocHub-ULB/DocHub#140]
# Feature description

Add sorting or classification method for own courses by year.

Something like this:

![folder system](https://user-images.githubusercontent.com/11949750/40489598-bd95cae8-5f69-11e8-808f-651b226cffcf.PNG)

# Changes needed

User model would need to be updated so that existing folders and the selected courses are sorted for the user.

Adding new course would require to specify date/folder or none to allow for unclassified courses.

CSS probably would need to be added to make it look nice.

Home and courses template would need to account for possible folders.

# Who can do this?

I can try to take a look at exactly how to go about it, but it requires at least one change to the User model and I am not comfortable enough with how it was exactly created to modify it so much. Also, it would touch a few other areas of development and I am unsure as to at what stage there so I don't want to cause merge conflicts or errors.

**Comment by C4ptainCrunch** [comment]
This seems a bit complex and too far fetched for our dev/maintenance capacity, so I'm closing it. Also I guess that most probably, our users will prefer to unsubscribe from old courses instead of keeping them in their list.

 Feel free to reopen if anybody feels it's a priority :)
