### ISSUE TITLE
Référencer UrLab et le CI

### ISSUE THREAD

**Issue by Minigrim0** [DocHub-ULB/DocHub#165]
Beaucoup de gens pensent que DocHub est géré par l'ULB. Ce serait bien et pour le CI et pour UrLab de les référencer en tant que fondateurs du projet dochub.

(Genre mettre 2 gros logos sur la page d'accueil)

**Comment by tperale** [comment]
Normalement il y a déjà un petit logo dans le footer du site mais oui c'est clairement pas une évidence, le mieux je pense ça serait d'avoir une page "about" où c'est bien expliqué.

**Comment by fgrimau** [comment]
En fait on en a parlé  en Réunion hier, en disant que le HS manquait de visibilité auprès des Ba1 en info c'est sur le [pad](https://pad.lqdn.fr/p/urlab-meeting-70) (au niveau "Événement 2ieme quadri)

**Comment by C4ptainCrunch** [comment]
Duplicate of #302
