### ISSUE TITLE
Use poetry as package manager

### ISSUE THREAD

**Issue by Mortinat** [DocHub-ULB/DocHub#261]
Le soucis actuel est que maintenir les libs a jour de façon correct est pas très simple. On a pip-tools mais il ne prend pas en compte les inter-dependence et ce contente juste de mettre les dernières versions disponible (si ca a pas changer depuis le temps) ce qui fait que faut tout retester a la main etc. Ou poetry lui fait plus attention a ce genre de chose et un simple pytest peut suffir car on peu lui faire plus confiance.

De plus poetry aide a réduire le nombre de tools nécessaire pour devs, vu qu'il remplace pip, venv et pip-tools, les nouveaux devs n'auront qu'un tools a maîtriser (meme si pip et venv nous semble trivial plusieurs ba1 et ba2 ne connaissent pas ces tools). Il semblerait que pyproject.toml va devenir un standard dans le futur de python meme si poetry ne sera peut etre pas le tool principal.

TLDR: poetry rend plus simple l'update des dependence et réduit le nombre de tools

**Comment by titouanc** [comment]
> On a pip-tools mais il ne prend pas en compte les inter-dependence et ce contente juste de mettre les dernières versions disponible (si ca a pas changer depuis le temps) ce qui fait que faut tout retester a la main etc.

Je ne suis pas sûr de comprendre :thinking: Je vois 3 cas possibles:
1. Un package est updaté à une version plus récente et casse quelque chose (imports ou un test ne passe plus) -> c'est vérifié dans la CI
2. Un package est updaté à une version et casse quelque chose silencieusement (les tests passent, mais l'application ne se comporte plus comme prévu) -> il faut ajouter un test pour ça, et de toute façon poetry ne peut pas détecter ce cas
3. Un package est updaté, rien ne casse et tout va bien -> no problem

Par ailleurs, la mise à jour des fichiers de requirements est très bien supporté par @dependabot, ou simplement avec `pip-compile --upgrade-package <pkg-name>` 

L'un dans l'autre, à part ajouter un nouvel outil je ne vois pas en quoi poetry améliore la situation. De plus, cela rajoute un problème d'oeuf et de poule (j'imagine il faut `pip install poetry` pour commencer à utiliser le projet ?). Enfin, il faudra toujours penser à lancer les commandes avec `poetry run ...`, ce qui risque simplement d'augmenter le nombre d'erreurs humaines.

**Comment by titouanc** [comment]
> Il m'est déjà arrive que update une lib casse un truc de façon silencieuse car une lib était "trop a jour" pour une autre lib.

Dans ce cas, les tests cassent, tu merge juste pas la PR ?

**Comment by Mortinat** [comment]
Non car ca peut être des libs genre dal qui ont pas de test dédier

**Comment by titouanc** [comment]
En quoi serait-ce différent avec poetry ?

**Comment by Mortinat** [comment]
poetry gère interdépendances des libs . Avant d'update une lib il vérifie que cela ne va casser aucune autre dépendances

**Comment by C4ptainCrunch** [comment]
Il me semble que pip-tools fait le même check. https://stackoverflow.com/a/65285710/1430325

**Comment by Mortinat** [comment]
My bad au moment ou on l'avais utiliser on avait eu un soucis a cause de ca. Mais reste que pourquoi utiliser 3 tools quand on peut en avoir un ? + pyproject.toml devrai devenir un standard pour python cf [PEP518](https://peps.python.org/pep-0518/) donc pourquoi ne pas déjà l'utiliser ?

**Comment by Bruno-brsy** [comment]
En soit, d'utiliser `poetry` n'est pas beaucoup plus complexe que la suite `pip` et `poetry` peut s'installer directement par lui-même: https://python-poetry.org/docs/ par exemple: `curl -sSL https://install.python-poetry.org | python3 -`

Je ne suis pas sûr de comprendre pourquoi autant de frein à utiliser `poetry`

**Comment by C4ptainCrunch** [comment]
De ce que je comprends l'avantage de `poetry` c'est que c'est un tool unique pour faire de la gestion de venv, de dépendances et d'upgrade + que c'est "moderne". 

> En plus, s'il permet de centraliser les vérifications de dépendance et de lib

Il n'y a pas de différence entre pip-tools et poetry de ce côté là. Jusqu'à preuve du contraire, les 2 ont un bon algo de dependency resolution et les 2 supportent `pyproject.toml`

-------

Mon avis c'est qu'un dev python ne sait pas se raisonnablement débrouiller sans connaitre les venv et pip. Y'a encore beaucoup trop de projets qui les utilisent et ca reste la méthode pronée par la PSF et PyPA.

Donc si les gens sont obligés de connaitre venv et pip, pourquoi leur faire apprendre un 3ème tool (poetry) qui fait la même chose ?

(oui, il y a des BA1, potentiels contributeurs de dochub, qui n'ont jamais entendu parler des venv, mais amha, ce n'est pas un service de leur en cacher l'existence, ils devront bien l'apprendre pour un autre projet quand même)

Le seul truc "pas standard"/"pas obligé d'apprendre" c'est `pip-tools`, mais mon avis là dessus, on ne doit y toucher que pour upgrade des deps ou en rajouter, ce qui est quelque chose qu'il n'y a que les core devs ou le mainteneur qui font. Et eux, ils connaissent déjà `pip-tools` donc `poetry` n'est pas un avantage non plus ici


> Je ne suis pas sûr de comprendre pourquoi autant de frein à utiliser poetry

Mon argumentaire se résume en: 
1. if it aint broke dont fix it
2. keep it simple, keep it standard => less is more

**Comment by Mortinat** [comment]
Mais justement actuellement je pense on doit être 3-4 a activement regarder ce qui se passe autour de dochub et on est déjà 2 a utilisé `poetry` pour la (casi) totalité de nos projets. De plus `pip-tools` a deux trois trucs qui manque (ou qui ne semble pas explicite) du style avoir un seul fichier pour toutes nos dépendances (dev prod test), les commandes sont moins intuitives que `poetry`. Puis si on veut parler au plus grand nombre `poetry `semble meilleur choix 22,4k stars pour `poetry` vs 6.3k pour` pip-tools`

**Comment by Mortinat** [comment]
Comme dis dans la pr c'est pour ce genre de truc que je trouve pip + venv moins pratique que poetry
![image](https://user-images.githubusercontent.com/43477020/206715264-a2086b3d-ac46-4aaa-9212-8d6b80a624fc.png)

**Comment by C4ptainCrunch** [comment]
The Python packaging ecosystem is still a mess and changing too fast, let's close this for the moment. When there is a clear winner, let's revisit this ticket :)

https://pradyunsg.me/blog/2023/01/21/pdm-does-not-implement-pep-582/
https://pradyunsg.me/blog/2023/01/21/thoughts-on-python-packaging/
